'''
This file is going to implement the claude function from the mylib.LLMbot module as an Api-Endpoint using FastAPI. The endpoint will accept a POST request with a JSON payload containing the topic and the number of sentences for the summary. The response will be a JSON object containing the summary generated by Claude. we will also use uvicorn to run the FastAPI application. The endpoint will be accessible at /summarize. pydantic will be used to validate the input data.
'''

import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from mylib.LLMbot import claude

app = FastAPI()

class SummarizeRequest(BaseModel):
    topic: str = Field(min_length=1)
    sentences: int = Field(gt=0)

@app.post("/summarize")
async def summarize(request: SummarizeRequest):
    try:
        topic = request.topic
        sentences = request.sentences
        summary = claude(topic, sentences)
        return {"summary": summary}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/")
async def root():
    return {"message": "Welcome to the Claude summarization API. Use the /summarize endpoint to get summaries."}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)