name: CI Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with:
             python-version: 3.11
        - name: install
          run: make install
        - name: format
          run: make format
        - name: debug
          run: make lint
        - name: test
          env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          run: make test
